"""initial schema

Revision ID: 325f3dcc43d9
Revises: 
Create Date: 2026-02-02 16:35:08.593230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '325f3dcc43d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_critic_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('target_type', sa.Enum('WORLD', 'STORY', 'CONVERSATION', name='critictargettype'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_isms_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('critic_created_at_idx', 'platform_critic_evaluations', ['created_at'], unique=False)
    op.create_index('critic_score_idx', 'platform_critic_evaluations', ['overall_score'], unique=False)
    op.create_index('critic_target_idx', 'platform_critic_evaluations', ['target_type', 'target_id'], unique=False)
    op.create_table('platform_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('HUMAN', 'AGENT', name='usertype'), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=128), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('user_type_idx', 'platform_users', ['type'], unique=False)
    op.create_index('user_username_idx', 'platform_users', ['username'], unique=False)
    op.create_table('studio_communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('from_agent', sa.String(length=50), nullable=False),
    sa.Column('to_agent', sa.String(length=50), nullable=True),
    sa.Column('message_type', sa.Enum('FEEDBACK', 'REQUEST', 'CLARIFICATION', 'RESPONSE', 'APPROVAL', name='studiocommunicationtype'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('in_reply_to', sa.UUID(), nullable=True),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('tool_used', sa.String(length=100), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['in_reply_to'], ['studio_communications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('studio_comm_content_id_idx', 'studio_communications', ['content_id'], unique=False)
    op.create_index('studio_comm_from_agent_idx', 'studio_communications', ['from_agent'], unique=False)
    op.create_index('studio_comm_resolved_idx', 'studio_communications', ['resolved'], unique=False)
    op.create_index('studio_comm_thread_idx', 'studio_communications', ['thread_id'], unique=False)
    op.create_index('studio_comm_timestamp_idx', 'studio_communications', ['timestamp'], unique=False)
    op.create_index('studio_comm_to_agent_idx', 'studio_communications', ['to_agent'], unique=False)
    op.create_table('platform_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('api_key_user_idx', 'platform_api_keys', ['user_id'], unique=False)
    op.create_table('platform_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('comment_created_at_idx', 'platform_comments', ['created_at'], unique=False)
    op.create_index('comment_parent_idx', 'platform_comments', ['parent_id'], unique=False)
    op.create_index('comment_target_idx', 'platform_comments', ['target_type', 'target_id'], unique=False)
    op.create_index('comment_user_idx', 'platform_comments', ['user_id'], unique=False)
    op.create_table('platform_social_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('interaction_type', sa.String(length=20), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['platform_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('social_target_idx', 'platform_social_interactions', ['target_type', 'target_id'], unique=False)
    op.create_index('social_unique_idx', 'platform_social_interactions', ['user_id', 'target_type', 'target_id', 'interaction_type'], unique=False)
    op.create_index('social_user_idx', 'platform_social_interactions', ['user_id'], unique=False)
    op.create_table('platform_worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('year_setting', sa.Integer(), nullable=False),
    sa.Column('causal_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scientific_basis', sa.Text(), nullable=True),
    sa.Column('canon_summary', sa.Text(), nullable=True),
    sa.Column('regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dweller_count', sa.Integer(), nullable=False),
    sa.Column('story_count', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['platform_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('world_active_idx', 'platform_worlds', ['is_active'], unique=False)
    op.create_index('world_created_at_idx', 'platform_worlds', ['created_at'], unique=False)
    op.create_table('platform_agent_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_type', sa.Enum('PRODUCTION', 'WORLD_CREATOR', 'DWELLER', 'STORYTELLER', 'CRITIC', 'PUPPETEER', name='agenttype'), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('world_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('activity_agent_type_idx', 'platform_agent_activity', ['agent_type'], unique=False)
    op.create_index('activity_timestamp_idx', 'platform_agent_activity', ['timestamp'], unique=False)
    op.create_index('activity_world_idx', 'platform_agent_activity', ['world_id'], unique=False)
    op.create_table('platform_agent_traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_type', sa.Enum('PRODUCTION', 'WORLD_CREATOR', 'DWELLER', 'STORYTELLER', 'CRITIC', 'PUPPETEER', name='agenttype'), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=True),
    sa.Column('world_id', sa.UUID(), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('parsed_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('trace_agent_type_idx', 'platform_agent_traces', ['agent_type'], unique=False)
    op.create_index('trace_operation_idx', 'platform_agent_traces', ['operation'], unique=False)
    op.create_index('trace_timestamp_idx', 'platform_agent_traces', ['timestamp'], unique=False)
    op.create_index('trace_world_idx', 'platform_agent_traces', ['world_id'], unique=False)
    op.create_table('platform_aspects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('aspect_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canon_justification', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'APPROVED', 'REJECTED', name='aspectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('aspect_agent_idx', 'platform_aspects', ['agent_id'], unique=False)
    op.create_index('aspect_created_at_idx', 'platform_aspects', ['created_at'], unique=False)
    op.create_index('aspect_status_idx', 'platform_aspects', ['status'], unique=False)
    op.create_index('aspect_type_idx', 'platform_aspects', ['aspect_type'], unique=False)
    op.create_index('aspect_world_idx', 'platform_aspects', ['world_id'], unique=False)
    op.create_table('platform_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('conversation_updated_idx', 'platform_conversations', ['updated_at'], unique=False)
    op.create_index('conversation_world_idx', 'platform_conversations', ['world_id'], unique=False)
    op.create_table('platform_dwellers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('inhabited_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin_region', sa.String(length=100), nullable=False),
    sa.Column('generation', sa.String(length=50), nullable=False),
    sa.Column('name_context', sa.Text(), nullable=False),
    sa.Column('cultural_identity', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Text(), nullable=False),
    sa.Column('background', sa.Text(), nullable=False),
    sa.Column('core_memories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('personality_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('episodic_memories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_summaries', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationship_memories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_situation', sa.Text(), nullable=False),
    sa.Column('working_memory_size', sa.Integer(), nullable=False),
    sa.Column('current_region', sa.String(length=100), nullable=True),
    sa.Column('specific_location', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['inhabited_by'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('dweller_available_idx', 'platform_dwellers', ['is_available'], unique=False)
    op.create_index('dweller_created_by_idx', 'platform_dwellers', ['created_by'], unique=False)
    op.create_index('dweller_inhabited_by_idx', 'platform_dwellers', ['inhabited_by'], unique=False)
    op.create_index('dweller_world_idx', 'platform_dwellers', ['world_id'], unique=False)
    op.create_table('platform_production_briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('research_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_recommendation', sa.Integer(), nullable=True),
    sa.Column('resulting_world_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CREATING', 'COMPLETED', 'FAILED', name='briefstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resulting_world_id'], ['platform_worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('brief_created_at_idx', 'platform_production_briefs', ['created_at'], unique=False)
    op.create_index('brief_status_idx', 'platform_production_briefs', ['status'], unique=False)
    op.create_table('platform_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('year_setting', sa.Integer(), nullable=False),
    sa.Column('causal_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scientific_basis', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'APPROVED', 'REJECTED', name='proposalstatus'), nullable=False),
    sa.Column('resulting_world_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['resulting_world_id'], ['platform_worlds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('proposal_agent_idx', 'platform_proposals', ['agent_id'], unique=False)
    op.create_index('proposal_created_at_idx', 'platform_proposals', ['created_at'], unique=False)
    op.create_index('proposal_status_idx', 'platform_proposals', ['status'], unique=False)
    op.create_table('platform_stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SHORT', 'LONG', name='storytype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('reaction_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_status', sa.Enum('PENDING', 'GENERATING', 'COMPLETE', 'FAILED', name='generationstatus'), nullable=False),
    sa.Column('generation_job_id', sa.String(length=255), nullable=True),
    sa.Column('generation_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('story_created_at_idx', 'platform_stories', ['created_at'], unique=False)
    op.create_index('story_type_idx', 'platform_stories', ['type'], unique=False)
    op.create_index('story_world_idx', 'platform_stories', ['world_id'], unique=False)
    op.create_table('platform_world_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('ENVIRONMENTAL', 'SOCIETAL', 'TECHNOLOGICAL', 'BACKGROUND', name='worldeventtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('world_event_active_idx', 'platform_world_events', ['is_active'], unique=False)
    op.create_index('world_event_timestamp_idx', 'platform_world_events', ['timestamp'], unique=False)
    op.create_index('world_event_type_idx', 'platform_world_events', ['event_type'], unique=False)
    op.create_index('world_event_world_idx', 'platform_world_events', ['world_id'], unique=False)
    op.create_table('platform_aspect_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aspect_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('STRENGTHEN', 'APPROVE', 'REJECT', name='validationverdict'), nullable=False),
    sa.Column('critique', sa.Text(), nullable=False),
    sa.Column('canon_conflicts', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('suggested_fixes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('updated_canon_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['aspect_id'], ['platform_aspects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('aspect_validation_agent_idx', 'platform_aspect_validations', ['agent_id'], unique=False)
    op.create_index('aspect_validation_aspect_idx', 'platform_aspect_validations', ['aspect_id'], unique=False)
    op.create_index('aspect_validation_created_at_idx', 'platform_aspect_validations', ['created_at'], unique=False)
    op.create_index('aspect_validation_unique_idx', 'platform_aspect_validations', ['aspect_id', 'agent_id'], unique=True)
    op.create_table('platform_conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('dweller_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['platform_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dweller_id'], ['platform_dwellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('message_conversation_idx', 'platform_conversation_messages', ['conversation_id'], unique=False)
    op.create_index('message_timestamp_idx', 'platform_conversation_messages', ['timestamp'], unique=False)
    op.create_table('platform_dweller_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dweller_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['dweller_id'], ['platform_dwellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('action_actor_idx', 'platform_dweller_actions', ['actor_id'], unique=False)
    op.create_index('action_created_at_idx', 'platform_dweller_actions', ['created_at'], unique=False)
    op.create_index('action_dweller_idx', 'platform_dweller_actions', ['dweller_id'], unique=False)
    op.create_index('action_type_idx', 'platform_dweller_actions', ['action_type'], unique=False)
    op.create_table('platform_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('STRENGTHEN', 'APPROVE', 'REJECT', name='validationverdict'), nullable=False),
    sa.Column('critique', sa.Text(), nullable=False),
    sa.Column('scientific_issues', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('suggested_fixes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['platform_users.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['platform_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('validation_agent_idx', 'platform_validations', ['agent_id'], unique=False)
    op.create_index('validation_created_at_idx', 'platform_validations', ['created_at'], unique=False)
    op.create_index('validation_proposal_idx', 'platform_validations', ['proposal_id'], unique=False)
    op.create_index('validation_unique_idx', 'platform_validations', ['proposal_id', 'agent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('validation_unique_idx', table_name='platform_validations')
    op.drop_index('validation_proposal_idx', table_name='platform_validations')
    op.drop_index('validation_created_at_idx', table_name='platform_validations')
    op.drop_index('validation_agent_idx', table_name='platform_validations')
    op.drop_table('platform_validations')
    op.drop_index('action_type_idx', table_name='platform_dweller_actions')
    op.drop_index('action_dweller_idx', table_name='platform_dweller_actions')
    op.drop_index('action_created_at_idx', table_name='platform_dweller_actions')
    op.drop_index('action_actor_idx', table_name='platform_dweller_actions')
    op.drop_table('platform_dweller_actions')
    op.drop_index('message_timestamp_idx', table_name='platform_conversation_messages')
    op.drop_index('message_conversation_idx', table_name='platform_conversation_messages')
    op.drop_table('platform_conversation_messages')
    op.drop_index('aspect_validation_unique_idx', table_name='platform_aspect_validations')
    op.drop_index('aspect_validation_created_at_idx', table_name='platform_aspect_validations')
    op.drop_index('aspect_validation_aspect_idx', table_name='platform_aspect_validations')
    op.drop_index('aspect_validation_agent_idx', table_name='platform_aspect_validations')
    op.drop_table('platform_aspect_validations')
    op.drop_index('world_event_world_idx', table_name='platform_world_events')
    op.drop_index('world_event_type_idx', table_name='platform_world_events')
    op.drop_index('world_event_timestamp_idx', table_name='platform_world_events')
    op.drop_index('world_event_active_idx', table_name='platform_world_events')
    op.drop_table('platform_world_events')
    op.drop_index('story_world_idx', table_name='platform_stories')
    op.drop_index('story_type_idx', table_name='platform_stories')
    op.drop_index('story_created_at_idx', table_name='platform_stories')
    op.drop_table('platform_stories')
    op.drop_index('proposal_status_idx', table_name='platform_proposals')
    op.drop_index('proposal_created_at_idx', table_name='platform_proposals')
    op.drop_index('proposal_agent_idx', table_name='platform_proposals')
    op.drop_table('platform_proposals')
    op.drop_index('brief_status_idx', table_name='platform_production_briefs')
    op.drop_index('brief_created_at_idx', table_name='platform_production_briefs')
    op.drop_table('platform_production_briefs')
    op.drop_index('dweller_world_idx', table_name='platform_dwellers')
    op.drop_index('dweller_inhabited_by_idx', table_name='platform_dwellers')
    op.drop_index('dweller_created_by_idx', table_name='platform_dwellers')
    op.drop_index('dweller_available_idx', table_name='platform_dwellers')
    op.drop_table('platform_dwellers')
    op.drop_index('conversation_world_idx', table_name='platform_conversations')
    op.drop_index('conversation_updated_idx', table_name='platform_conversations')
    op.drop_table('platform_conversations')
    op.drop_index('aspect_world_idx', table_name='platform_aspects')
    op.drop_index('aspect_type_idx', table_name='platform_aspects')
    op.drop_index('aspect_status_idx', table_name='platform_aspects')
    op.drop_index('aspect_created_at_idx', table_name='platform_aspects')
    op.drop_index('aspect_agent_idx', table_name='platform_aspects')
    op.drop_table('platform_aspects')
    op.drop_index('trace_world_idx', table_name='platform_agent_traces')
    op.drop_index('trace_timestamp_idx', table_name='platform_agent_traces')
    op.drop_index('trace_operation_idx', table_name='platform_agent_traces')
    op.drop_index('trace_agent_type_idx', table_name='platform_agent_traces')
    op.drop_table('platform_agent_traces')
    op.drop_index('activity_world_idx', table_name='platform_agent_activity')
    op.drop_index('activity_timestamp_idx', table_name='platform_agent_activity')
    op.drop_index('activity_agent_type_idx', table_name='platform_agent_activity')
    op.drop_table('platform_agent_activity')
    op.drop_index('world_created_at_idx', table_name='platform_worlds')
    op.drop_index('world_active_idx', table_name='platform_worlds')
    op.drop_table('platform_worlds')
    op.drop_index('social_user_idx', table_name='platform_social_interactions')
    op.drop_index('social_unique_idx', table_name='platform_social_interactions')
    op.drop_index('social_target_idx', table_name='platform_social_interactions')
    op.drop_table('platform_social_interactions')
    op.drop_index('comment_user_idx', table_name='platform_comments')
    op.drop_index('comment_target_idx', table_name='platform_comments')
    op.drop_index('comment_parent_idx', table_name='platform_comments')
    op.drop_index('comment_created_at_idx', table_name='platform_comments')
    op.drop_table('platform_comments')
    op.drop_index('api_key_user_idx', table_name='platform_api_keys')
    op.drop_table('platform_api_keys')
    op.drop_index('studio_comm_to_agent_idx', table_name='studio_communications')
    op.drop_index('studio_comm_timestamp_idx', table_name='studio_communications')
    op.drop_index('studio_comm_thread_idx', table_name='studio_communications')
    op.drop_index('studio_comm_resolved_idx', table_name='studio_communications')
    op.drop_index('studio_comm_from_agent_idx', table_name='studio_communications')
    op.drop_index('studio_comm_content_id_idx', table_name='studio_communications')
    op.drop_table('studio_communications')
    op.drop_index('user_username_idx', table_name='platform_users')
    op.drop_index('user_type_idx', table_name='platform_users')
    op.drop_table('platform_users')
    op.drop_index('critic_target_idx', table_name='platform_critic_evaluations')
    op.drop_index('critic_score_idx', table_name='platform_critic_evaluations')
    op.drop_index('critic_created_at_idx', table_name='platform_critic_evaluations')
    op.drop_table('platform_critic_evaluations')
    # ### end Alembic commands ###
