"""sync_schema_with_models

Revision ID: 93bbfb2c4512
Revises: 325f3dcc43d9
Create Date: 2026-02-02 18:44:23.543592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93bbfb2c4512'
down_revision: Union[str, None] = '325f3dcc43d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('trace_agent_type_idx'), table_name='platform_agent_traces')
    op.drop_index(op.f('trace_operation_idx'), table_name='platform_agent_traces')
    op.drop_index(op.f('trace_timestamp_idx'), table_name='platform_agent_traces')
    op.drop_index(op.f('trace_world_idx'), table_name='platform_agent_traces')
    op.drop_table('platform_agent_traces')
    op.drop_index(op.f('message_conversation_idx'), table_name='platform_conversation_messages')
    op.drop_index(op.f('message_timestamp_idx'), table_name='platform_conversation_messages')
    op.drop_table('platform_conversation_messages')
    op.drop_index(op.f('story_created_at_idx'), table_name='platform_stories')
    op.drop_index(op.f('story_type_idx'), table_name='platform_stories')
    op.drop_index(op.f('story_world_idx'), table_name='platform_stories')
    op.drop_table('platform_stories')
    op.drop_index(op.f('activity_agent_type_idx'), table_name='platform_agent_activity')
    op.drop_index(op.f('activity_timestamp_idx'), table_name='platform_agent_activity')
    op.drop_index(op.f('activity_world_idx'), table_name='platform_agent_activity')
    op.drop_table('platform_agent_activity')
    op.drop_index(op.f('studio_comm_content_id_idx'), table_name='studio_communications')
    op.drop_index(op.f('studio_comm_from_agent_idx'), table_name='studio_communications')
    op.drop_index(op.f('studio_comm_resolved_idx'), table_name='studio_communications')
    op.drop_index(op.f('studio_comm_thread_idx'), table_name='studio_communications')
    op.drop_index(op.f('studio_comm_timestamp_idx'), table_name='studio_communications')
    op.drop_index(op.f('studio_comm_to_agent_idx'), table_name='studio_communications')
    op.drop_table('studio_communications')
    op.drop_index(op.f('conversation_updated_idx'), table_name='platform_conversations')
    op.drop_index(op.f('conversation_world_idx'), table_name='platform_conversations')
    op.drop_table('platform_conversations')
    op.drop_index(op.f('critic_created_at_idx'), table_name='platform_critic_evaluations')
    op.drop_index(op.f('critic_score_idx'), table_name='platform_critic_evaluations')
    op.drop_index(op.f('critic_target_idx'), table_name='platform_critic_evaluations')
    op.drop_table('platform_critic_evaluations')
    op.drop_index(op.f('brief_created_at_idx'), table_name='platform_production_briefs')
    op.drop_index(op.f('brief_status_idx'), table_name='platform_production_briefs')
    op.drop_table('platform_production_briefs')
    op.drop_index(op.f('world_event_active_idx'), table_name='platform_world_events')
    op.drop_index(op.f('world_event_timestamp_idx'), table_name='platform_world_events')
    op.drop_index(op.f('world_event_type_idx'), table_name='platform_world_events')
    op.drop_index(op.f('world_event_world_idx'), table_name='platform_world_events')
    op.drop_table('platform_world_events')
    op.add_column('platform_comments', sa.Column('reaction', sa.String(length=20), nullable=True))
    op.add_column('platform_dwellers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('platform_dwellers', sa.Column('last_action_at', sa.DateTime(), nullable=True))
    op.add_column('platform_users', sa.Column('platform_notifications', sa.Boolean(), nullable=False))
    op.add_column('platform_worlds', sa.Column('comment_count', sa.Integer(), nullable=False))
    op.add_column('platform_worlds', sa.Column('reaction_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('platform_worlds', 'story_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_worlds', sa.Column('story_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('platform_worlds', 'reaction_counts')
    op.drop_column('platform_worlds', 'comment_count')
    op.drop_column('platform_users', 'platform_notifications')
    op.drop_column('platform_dwellers', 'last_action_at')
    op.drop_column('platform_dwellers', 'is_active')
    op.drop_column('platform_comments', 'reaction')
    op.create_table('platform_world_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('world_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', postgresql.ENUM('ENVIRONMENTAL', 'SOCIETAL', 'TECHNOLOGICAL', 'BACKGROUND', name='worldeventtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], name=op.f('platform_world_events_world_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_world_events_pkey'))
    )
    op.create_index(op.f('world_event_world_idx'), 'platform_world_events', ['world_id'], unique=False)
    op.create_index(op.f('world_event_type_idx'), 'platform_world_events', ['event_type'], unique=False)
    op.create_index(op.f('world_event_timestamp_idx'), 'platform_world_events', ['timestamp'], unique=False)
    op.create_index(op.f('world_event_active_idx'), 'platform_world_events', ['is_active'], unique=False)
    op.create_table('platform_production_briefs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('research_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('selected_recommendation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resulting_world_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CREATING', 'COMPLETED', 'FAILED', name='briefstatus'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resulting_world_id'], ['platform_worlds.id'], name=op.f('platform_production_briefs_resulting_world_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_production_briefs_pkey'))
    )
    op.create_index(op.f('brief_status_idx'), 'platform_production_briefs', ['status'], unique=False)
    op.create_index(op.f('brief_created_at_idx'), 'platform_production_briefs', ['created_at'], unique=False)
    op.create_table('platform_critic_evaluations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('target_type', postgresql.ENUM('WORLD', 'STORY', 'CONVERSATION', name='critictargettype'), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('ai_isms_detected', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_critic_evaluations_pkey'))
    )
    op.create_index(op.f('critic_target_idx'), 'platform_critic_evaluations', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('critic_score_idx'), 'platform_critic_evaluations', ['overall_score'], unique=False)
    op.create_index(op.f('critic_created_at_idx'), 'platform_critic_evaluations', ['created_at'], unique=False)
    op.create_table('platform_conversations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('world_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], name=op.f('platform_conversations_world_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_conversations_pkey'))
    )
    op.create_index(op.f('conversation_world_idx'), 'platform_conversations', ['world_id'], unique=False)
    op.create_index(op.f('conversation_updated_idx'), 'platform_conversations', ['updated_at'], unique=False)
    op.create_table('studio_communications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('from_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('to_agent', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('message_type', postgresql.ENUM('FEEDBACK', 'REQUEST', 'CLARIFICATION', 'RESPONSE', 'APPROVAL', name='studiocommunicationtype'), autoincrement=False, nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('thread_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('in_reply_to', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tool_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['in_reply_to'], ['studio_communications.id'], name=op.f('studio_communications_in_reply_to_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('studio_communications_pkey'))
    )
    op.create_index(op.f('studio_comm_to_agent_idx'), 'studio_communications', ['to_agent'], unique=False)
    op.create_index(op.f('studio_comm_timestamp_idx'), 'studio_communications', ['timestamp'], unique=False)
    op.create_index(op.f('studio_comm_thread_idx'), 'studio_communications', ['thread_id'], unique=False)
    op.create_index(op.f('studio_comm_resolved_idx'), 'studio_communications', ['resolved'], unique=False)
    op.create_index(op.f('studio_comm_from_agent_idx'), 'studio_communications', ['from_agent'], unique=False)
    op.create_index(op.f('studio_comm_content_id_idx'), 'studio_communications', ['content_id'], unique=False)
    op.create_table('platform_agent_activity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('agent_type', postgresql.ENUM('PRODUCTION', 'WORLD_CREATOR', 'DWELLER', 'STORYTELLER', 'CRITIC', 'PUPPETEER', name='agenttype'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], name=op.f('platform_agent_activity_world_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_agent_activity_pkey'))
    )
    op.create_index(op.f('activity_world_idx'), 'platform_agent_activity', ['world_id'], unique=False)
    op.create_index(op.f('activity_timestamp_idx'), 'platform_agent_activity', ['timestamp'], unique=False)
    op.create_index(op.f('activity_agent_type_idx'), 'platform_agent_activity', ['agent_type'], unique=False)
    op.create_table('platform_stories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('world_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('SHORT', 'LONG', name='storytype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('thumbnail_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction_counts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generation_status', postgresql.ENUM('PENDING', 'GENERATING', 'COMPLETE', 'FAILED', name='generationstatus'), autoincrement=False, nullable=False),
    sa.Column('generation_job_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('generation_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['platform_users.id'], name=op.f('platform_stories_created_by_fkey')),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], name=op.f('platform_stories_world_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_stories_pkey'))
    )
    op.create_index(op.f('story_world_idx'), 'platform_stories', ['world_id'], unique=False)
    op.create_index(op.f('story_type_idx'), 'platform_stories', ['type'], unique=False)
    op.create_index(op.f('story_created_at_idx'), 'platform_stories', ['created_at'], unique=False)
    op.create_table('platform_conversation_messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dweller_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['platform_conversations.id'], name=op.f('platform_conversation_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dweller_id'], ['platform_dwellers.id'], name=op.f('platform_conversation_messages_dweller_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_conversation_messages_pkey'))
    )
    op.create_index(op.f('message_timestamp_idx'), 'platform_conversation_messages', ['timestamp'], unique=False)
    op.create_index(op.f('message_conversation_idx'), 'platform_conversation_messages', ['conversation_id'], unique=False)
    op.create_table('platform_agent_traces',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('agent_type', postgresql.ENUM('PRODUCTION', 'WORLD_CREATOR', 'DWELLER', 'STORYTELLER', 'CRITIC', 'PUPPETEER', name='agenttype'), autoincrement=False, nullable=False),
    sa.Column('agent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('world_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tokens_in', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tokens_out', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parsed_output', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['world_id'], ['platform_worlds.id'], name=op.f('platform_agent_traces_world_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('platform_agent_traces_pkey'))
    )
    op.create_index(op.f('trace_world_idx'), 'platform_agent_traces', ['world_id'], unique=False)
    op.create_index(op.f('trace_timestamp_idx'), 'platform_agent_traces', ['timestamp'], unique=False)
    op.create_index(op.f('trace_operation_idx'), 'platform_agent_traces', ['operation'], unique=False)
    op.create_index(op.f('trace_agent_type_idx'), 'platform_agent_traces', ['agent_type'], unique=False)
    # ### end Alembic commands ###
